// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhkmsfjworlrmwepmrgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoa21zZmp3b3Jscm13ZXBtcmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDA2MTMsImV4cCI6MjA3MzExNjYxM30.xCr-68yq0KPOEazNeDSJbe3tyKzmeICzawMevoqt02s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});